server:
  port: ${APP_PORT:8080}
logging:
  level:
    com.turnrut: debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: getway
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
    zipkin:
      base-url: http://localhost:9411/ # 指定了 Zipkin 服务器的地址
# zuul整合eureka后自动转发
#zuul:
#  routes:
#    alice:
#      path: /alice/**
#      serviceId: alice
#    bob:
#      path: /bob/**
#      serviceId: bob
